// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/AutoDivdik/rmq"
	"github.com/rabbitmq/amqp091-go"
)

// Injectors from wire.go:

func InitApp(connStr rmq.RabbitMQConnStr) (*App, func(), error) {
	connection, cleanup, err := initRabbitMQ(connStr)
	if err != nil {
		return nil, nil, err
	}
	eventConsumer, err := rmq.NewConsumer(connection)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	app := NewApplication(connection, eventConsumer)
	return app, func() {
		cleanup()
	}, nil
}

// wire.go:

func initRabbitMQ(url rmq.RabbitMQConnStr) (*amqp091.Connection, func(), error) {
	conn, err := rmq.NewRabbitMQConn(url, 5, 2)
	if err != nil {
		return nil, nil, err
	}

	return conn, func() { conn.Close() }, nil
}
